image: maven:eclipse-temurin

stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - echo "Building the application"
    - mvn clean package
    - echo "Build finished"

test:
  stage: test
  script:
    - echo "Testing the application"
    - mvn test
    - echo "Test finished"

package:
  stage: package
  script:
    - echo "Packaging the application"
    - mvn package
    - echo "Package finished"

